/**
 * Pages légales (anglais = version de référence, traduction française).
 * MODÈLE À FAIRE RELIRE PAR UN AVOCAT avant le lancement. Variables : {brand}, {company}, {email}.
 */
export type LegalDoc = "terms" | "privacy" | "refund";
export interface LegalSection { h: string; p: string[] }

export const LEGAL_UPDATED = "2026-09-27";

export const LEGAL: Record<LegalDoc, { en: LegalSection[]; fr: LegalSection[] }> = {
  terms: {
    en: [
      { h: "1. Who we are", p: ["{brand} is a software service operated by {company}, a limited liability company registered in Florida, United States. Contact: {email}.", "{brand} is an independent tool. It is not affiliated with, endorsed or sponsored by eBay Inc., CJDropshipping or AliExpress."] },
      { h: "2. The service", p: ["{brand} helps online sellers find products, estimate margins, create eBay listings, place orders with suppliers and send tracking numbers, through the official APIs of these platforms.", "The service is intended for professional sellers acting for the purposes of their business. By creating an account, you confirm that you use it for business purposes and that you are at least 18 years old."] },
      { h: "3. Your account", p: ["You are responsible for keeping your password confidential and for all activity on your account. Tell us immediately at {email} if you suspect unauthorized use.", "You authorize {brand} to act on your connected eBay and supplier accounts only to perform the actions you request or enable (publishing listings, updating quantities, placing and paying supplier orders with your supplier balance, sending tracking numbers). You can disconnect these accounts at any time."] },
      { h: "4. Your responsibilities as a seller", p: ["You remain the seller of record. You are solely responsible for complying with eBay's policies (including its dropshipping, VeRO and product safety policies), consumer protection, tax, customs and product safety laws in every country where you sell, and for your relationship with your buyers and suppliers.", "{brand} includes safeguards (margin threshold, protected brand filter, daily listing limits, loss protection on orders), but these are aids, not guarantees. You must review your listings and orders."] },
      { h: "5. No guarantee of results", p: ["Prices, fees, stock and delivery times come from third parties and can change at any time. Margin estimates are estimates. {brand} does not guarantee any sales, profit or the continued availability of eBay, supplier or payment services."] },
      { h: "6. Plans, trial and payment", p: ["Paid plans are billed in advance, monthly or yearly, through Stripe. New customers get one 3-day trial for $0.99, charged at sign-up; the plan you chose is charged at the end of the trial unless you cancel before.", "Subscriptions renew automatically until cancelled. You can cancel at any time from your account; cancellation takes effect at the end of the current billing period. Prices may change with at least 30 days' notice by email.", "Refunds are covered by our Refund Policy."] },
      { h: "7. Affiliate program", p: ["Affiliates earn a commission on payments made by the customers they refer, as shown in their account. Commissions become payable after a 30-day refund period and are paid once the balance reaches the minimum shown. Self-referrals, fraud, spam and misleading advertising void all commissions. We may change or end the program with 30 days' notice; commissions already earned remain due."] },
      { h: "8. Acceptable use", p: ["You may not use {brand} to sell counterfeit, illegal or prohibited items, to infringe intellectual property, to source from retailers whose terms or eBay's policies forbid it, to overload or reverse engineer the service, or to access another user's data."] },
      { h: "9. Suspension and termination", p: ["We may suspend or close an account that breaches these terms or puts other users, platforms or {brand} at risk. You may close your account at any time by writing to {email}."] },
      { h: "10. Limitation of liability", p: ["To the maximum extent permitted by law, the service is provided \"as is\". {company} is not liable for indirect or consequential damages, lost profits, lost sales, account suspensions by third-party platforms, or supplier failures. Our total liability for any claim is limited to the amounts you paid us in the 12 months before the claim."] },
      { h: "11. Changes and governing law", p: ["We may update these terms; we will notify you of material changes by email at least 15 days in advance. These terms are governed by the laws of the State of Florida, United States, without prejudice to any mandatory rights you have under the law of your country."] },
    ],
    fr: [
      { h: "1. Qui sommes-nous", p: ["{brand} est un logiciel en ligne exploité par {company}, société à responsabilité limitée enregistrée en Floride (États-Unis). Contact : {email}.", "{brand} est un outil indépendant, sans lien avec eBay Inc., CJDropshipping ou AliExpress, qui ne le soutiennent ni ne le sponsorisent."] },
      { h: "2. Le service", p: ["{brand} aide les vendeurs en ligne à trouver des produits, estimer leurs marges, créer des annonces eBay, passer les commandes chez les fournisseurs et transmettre les numéros de suivi, via les API officielles de ces plateformes.", "Le service s'adresse aux vendeurs professionnels agissant pour leur activité. En créant un compte, vous confirmez l'utiliser à des fins professionnelles et avoir au moins 18 ans."] },
      { h: "3. Votre compte", p: ["Vous êtes responsable de la confidentialité de votre mot de passe et de toute activité sur votre compte. Prévenez-nous immédiatement à {email} en cas d'utilisation non autorisée.", "Vous autorisez {brand} à agir sur vos comptes eBay et fournisseurs connectés uniquement pour les actions que vous demandez ou activez (publication d'annonces, mise à jour des quantités, commandes payées avec votre solde fournisseur, envoi des numéros de suivi). Vous pouvez déconnecter ces comptes à tout moment."] },
      { h: "4. Vos responsabilités de vendeur", p: ["Vous restez le vendeur. Vous êtes seul responsable du respect des règles d'eBay (dont ses règles sur le dropshipping, le programme VeRO et la sécurité des produits), des lois sur la protection des consommateurs, la fiscalité, les douanes et la sécurité des produits dans chaque pays où vous vendez, ainsi que de vos relations avec vos acheteurs et fournisseurs.", "{brand} comprend des garde-fous (seuil de marge, filtre de marques protégées, limites quotidiennes, protection contre les commandes à perte), mais ce sont des aides, pas des garanties. Vous devez vérifier vos annonces et vos commandes."] },
      { h: "5. Aucune garantie de résultat", p: ["Les prix, frais, stocks et délais proviennent de tiers et peuvent changer à tout moment. Les marges affichées sont des estimations. {brand} ne garantit aucune vente, aucun profit, ni la disponibilité continue d'eBay, des fournisseurs ou des services de paiement."] },
      { h: "6. Formules, essai et paiement", p: ["Les formules payantes sont facturées à l'avance, au mois ou à l'année, via Stripe. Chaque nouveau client bénéficie d'un seul essai de 3 jours à 0,99 $, payé à l'inscription ; la formule choisie est facturée à la fin de l'essai sauf résiliation avant.", "Les abonnements se renouvellent automatiquement jusqu'à résiliation. Vous pouvez résilier à tout moment depuis votre compte ; la résiliation prend effet à la fin de la période en cours. Les prix peuvent évoluer avec un préavis d'au moins 30 jours par email.", "Les remboursements sont régis par notre politique de remboursement."] },
      { h: "7. Programme d'affiliation", p: ["Les affiliés touchent une commission sur les paiements des clients qu'ils recommandent, comme indiqué dans leur compte. Les commissions deviennent payables après une période de remboursement de 30 jours et sont versées dès que le solde atteint le minimum indiqué. L'auto-parrainage, la fraude, le spam et la publicité trompeuse annulent toutes les commissions. Nous pouvons modifier ou arrêter le programme avec 30 jours de préavis ; les commissions déjà acquises restent dues."] },
      { h: "8. Utilisation acceptable", p: ["Il est interdit d'utiliser {brand} pour vendre des articles contrefaits, illégaux ou interdits, pour porter atteinte à la propriété intellectuelle, pour s'approvisionner chez des détaillants dont les conditions ou les règles d'eBay l'interdisent, pour surcharger ou décompiler le service, ou pour accéder aux données d'un autre utilisateur."] },
      { h: "9. Suspension et résiliation", p: ["Nous pouvons suspendre ou fermer un compte qui enfreint ces conditions ou met en danger d'autres utilisateurs, les plateformes ou {brand}. Vous pouvez fermer votre compte à tout moment en écrivant à {email}."] },
      { h: "10. Limitation de responsabilité", p: ["Dans toute la mesure permise par la loi, le service est fourni « en l'état ». {company} n'est pas responsable des dommages indirects, pertes de profits ou de ventes, suspensions de comptes par des plateformes tierces ou défaillances des fournisseurs. Notre responsabilité totale est limitée aux sommes que vous nous avez versées au cours des 12 mois précédant la réclamation."] },
      { h: "11. Modifications et droit applicable", p: ["Nous pouvons modifier ces conditions ; les changements importants vous seront notifiés par email au moins 15 jours à l'avance. Ces conditions sont régies par le droit de l'État de Floride (États-Unis), sans préjudice des droits impératifs dont vous bénéficiez selon la loi de votre pays."] },
    ],
  },
  privacy: {
    en: [
      { h: "1. Controller", p: ["{company} (Florida, United States) operates {brand} and is responsible for your personal data. Contact for any privacy request: {email}."] },
      { h: "2. Data we collect", p: ["Account: email, password (stored hashed, never readable), language, plan, billing status (payment details are handled by Stripe; we never see your card number).", "Sign in with Google: if you choose it, Google sends us your email address, whether Google has verified it, and a Google account identifier. We never see your Google password and we do not access any other Google data.", "Connected accounts: access tokens for eBay and your supplier, stored encrypted; your listings, orders, amounts and tracking numbers.", "Your buyers' shipping details are read from eBay only at the moment an order is placed with the supplier, sent to the supplier to deliver the order, and are not stored in our database.", "Leads: the email you give us when using a free tool, if you choose to.", "Technical data: server logs (IP address, date, pages) kept for security for up to 30 days."] },
      { h: "3. Why we use it (legal bases)", p: ["To provide the service you signed up for (contract); to bill you and meet legal and tax obligations (legal obligation); to secure the service and prevent fraud (legitimate interest); to send service emails such as password resets, payment failures and order alerts (contract); to send you tips or offers only if you agreed (consent), with an unsubscribe link in every email."] },
      { h: "4. Who we share it with", p: ["Only the providers needed to run the service: eBay and your supplier (CJDropshipping) to perform the actions you request; Stripe (payments); Google (only if you sign in with Google); our hosting and database provider; Resend (emails); Anthropic (AI writing of listing texts: only product information is sent, never buyer data). We never sell your data."] },
      { h: "5. International transfers", p: ["Our servers and several providers are located in the United States. When data from the European Union or the United Kingdom is transferred, we rely on the providers' standard contractual clauses or equivalent safeguards."] },
      { h: "6. How long we keep it", p: ["Account data: as long as your account is open, then deleted within 90 days of closure, except invoices and accounting records kept as required by law (generally up to 7 years). Password reset links expire after 1 hour."] },
      { h: "7. Cookies", p: ["We use essential cookies only: session (keeps you logged in), lang (your language), consent (your cookie choice). With your consent, a ref cookie keeps the affiliate code you arrived with for 60 days; without consent, it is deleted when you close your browser. We use no advertising or third-party tracking cookies."] },
      { h: "8. Your rights", p: ["You can access, correct, export or delete your data, object to or restrict its use, and withdraw consent at any time by writing to {email}. We answer within 30 days. If you are in the EU or the UK, you can also complain to your data protection authority. California residents have the rights provided by the CCPA/CPRA; we do not sell or share personal information for cross-context advertising."] },
      { h: "9. Security", p: ["Passwords are hashed, platform tokens are encrypted at rest, connections use HTTPS, and access to data is limited to what is needed to run the service."] },
    ],
    fr: [
      { h: "1. Responsable du traitement", p: ["{company} (Floride, États-Unis) exploite {brand} et est responsable de vos données personnelles. Contact pour toute demande : {email}."] },
      { h: "2. Données collectées", p: ["Compte : email, mot de passe (stocké haché, jamais lisible), langue, formule, état de facturation (les données de paiement sont traitées par Stripe ; nous ne voyons jamais votre numéro de carte).", "Connexion avec Google : si vous la choisissez, Google nous transmet votre adresse email, l'information qu'elle est vérifiée et un identifiant de compte Google. Nous ne voyons jamais votre mot de passe Google et n'accédons à aucune autre donnée Google.", "Comptes connectés : jetons d'accès eBay et fournisseur, stockés chiffrés ; vos annonces, commandes, montants et numéros de suivi.", "Les coordonnées de livraison de vos acheteurs sont lues chez eBay uniquement au moment de commander chez le fournisseur, transmises au fournisseur pour livrer, et ne sont pas enregistrées dans notre base de données.", "Contacts : l'email que vous nous donnez en utilisant un outil gratuit, si vous le souhaitez.", "Données techniques : journaux du serveur (adresse IP, date, pages) conservés pour la sécurité jusqu'à 30 jours."] },
      { h: "3. Finalités et bases légales", p: ["Fournir le service souscrit (contrat) ; vous facturer et respecter nos obligations légales et fiscales (obligation légale) ; sécuriser le service et prévenir la fraude (intérêt légitime) ; envoyer les emails de service comme la réinitialisation du mot de passe, les échecs de paiement et les alertes de commandes (contrat) ; vous envoyer des conseils ou offres uniquement avec votre accord (consentement), avec un lien de désinscription dans chaque email."] },
      { h: "4. Destinataires", p: ["Uniquement les prestataires nécessaires au service : eBay et votre fournisseur (CJDropshipping) pour réaliser les actions que vous demandez ; Stripe (paiements) ; Google (uniquement si vous vous connectez avec Google) ; notre hébergeur et fournisseur de base de données ; Resend (emails) ; Anthropic (rédaction des annonces par IA : seules les informations produit sont envoyées, jamais les données des acheteurs). Nous ne vendons jamais vos données."] },
      { h: "5. Transferts internationaux", p: ["Nos serveurs et plusieurs prestataires sont situés aux États-Unis. Pour les données venant de l'Union européenne ou du Royaume-Uni, nous nous appuyons sur les clauses contractuelles types des prestataires ou des garanties équivalentes."] },
      { h: "6. Durée de conservation", p: ["Données du compte : tant que le compte est ouvert, puis supprimées dans les 90 jours suivant sa fermeture, sauf factures et pièces comptables conservées selon la loi (en général jusqu'à 7 ans). Les liens de réinitialisation expirent après 1 heure."] },
      { h: "7. Cookies", p: ["Nous utilisons uniquement des cookies essentiels : session (vous garder connecté), lang (votre langue), consent (votre choix de cookies). Avec votre accord, un cookie ref garde pendant 60 jours le code d'affiliation par lequel vous êtes arrivé ; sans accord, il est supprimé à la fermeture du navigateur. Aucun cookie publicitaire ni de pistage tiers."] },
      { h: "8. Vos droits", p: ["Vous pouvez accéder à vos données, les rectifier, les exporter ou les supprimer, vous opposer à leur utilisation ou la limiter, et retirer votre consentement à tout moment en écrivant à {email}. Nous répondons sous 30 jours. Si vous êtes dans l'UE ou au Royaume-Uni, vous pouvez aussi saisir votre autorité de protection des données (en France, la CNIL). Les résidents de Californie disposent des droits prévus par le CCPA/CPRA ; nous ne vendons ni ne partageons de données personnelles à des fins publicitaires."] },
      { h: "9. Sécurité", p: ["Les mots de passe sont hachés, les jetons des plateformes chiffrés au repos, les connexions passent en HTTPS, et l'accès aux données est limité au strict nécessaire."] },
    ],
  },
  refund: {
    en: [
      { h: "Trial", p: ["New customers get one 3-day trial for $0.99. The $0.99 trial fee is not refundable. Cancel before the end of the trial from your account and you will not be charged for the plan."] },
      { h: "Monthly plans", p: ["You can cancel at any time; your plan stays active until the end of the paid month. Months already started are not refunded."] },
      { h: "Yearly plans", p: ["If you are not satisfied, ask for a full refund within 14 days of your first yearly payment by writing to {email}. After 14 days, yearly plans are not refunded, but you can cancel the renewal at any time."] },
      { h: "Exceptions", p: ["If you were charged twice or by mistake, or if a major outage on our side prevented you from using the service, write to {email}: we will refund or credit the affected period. Nothing in this policy limits any refund right you have under mandatory law."] },
      { h: "How refunds are paid", p: ["Refunds go back to the original payment method through Stripe, usually within 5 to 10 business days. A refund cancels the affiliate commission on that payment."] },
    ],
    fr: [
      { h: "Essai", p: ["Chaque nouveau client bénéficie d'un seul essai de 3 jours à 0,99 $. Ces 0,99 $ ne sont pas remboursables. Résiliez avant la fin de l'essai depuis votre compte et la formule ne vous sera pas facturée."] },
      { h: "Formules mensuelles", p: ["Vous pouvez résilier à tout moment ; votre formule reste active jusqu'à la fin du mois payé. Les mois entamés ne sont pas remboursés."] },
      { h: "Formules annuelles", p: ["Si vous n'êtes pas satisfait, demandez un remboursement intégral dans les 14 jours suivant votre premier paiement annuel en écrivant à {email}. Au-delà de 14 jours, les formules annuelles ne sont pas remboursées, mais vous pouvez arrêter le renouvellement à tout moment."] },
      { h: "Exceptions", p: ["En cas de double prélèvement ou de paiement par erreur, ou si une panne importante de notre côté vous a empêché d'utiliser le service, écrivez à {email} : nous rembourserons ou créditerons la période concernée. Cette politique ne limite aucun droit à remboursement prévu par la loi."] },
      { h: "Versement des remboursements", p: ["Les remboursements sont faits sur le moyen de paiement d'origine via Stripe, en général sous 5 à 10 jours ouvrés. Un remboursement annule la commission d'affiliation liée à ce paiement."] },
    ],
  },
};
